#   _________________    _____            _________    _______       _______   ____    ____
#  /                /   /    /           / _____  /   / _____ \     / _____ \  \   \  /   /
# /___________     /   /    /           / /    / /   / /    / /    / /    / /   \   \/   /
#            /    /   /    /           / /    / /   / /____/ /    / /____/ /     \      /
#           /    /   /    /           / /    / /   / ______ \    / ______ \       \    /
#          /    /   /    /_______    / /    / /   / /     / /   / /     / /       /   /
#         /    /   /            /   / /____/ /   / /_____/ /   / /_____/ /       /   /
#        /____/   /____________/   /________/   /_________/   /_________/       /___/

#Use %player_name% to replace player name
#You need the PlaceHolderAPI for that!

#Colors:
#&0 - Black           | &8 - Dark Gray
#&1 - Dark blue       | &9 - Blue
#&2 - Dark green      | &a - Green
#&3 - Dark cyan       | &b - Cyan
#&4 - Dark red        | &c - Red
#&5 - Purple          | &d - Pink
#&6 - Orange          | &e - Yellow
#&7 - Gray            | &f - White

#Lettering options:
#&k - Random    | &n - Underlined
#&l - Bold     | &o - Italic
#&m - Track     | &r - Reset

#HEX to get hex color!
#Only in 1.16+
#&#ffffff

#Placeholders

#%xg7lobby_first_join%: returns the long of the first join of the player on the server;
#%xg7lobby_players_hiding%: returns if the player is hiding other players;
#%xg7lobby_pvp_enabled%: returns if the player is with pvp enabled;
#%xg7lobby_fly_enabled%: returns if the player is with fly enabled;
#%xg7lobby_build_enabled%: returns if the player is with build enabled;
#%xg7lobby_muted%: returns if the player is muted;
#%xg7lobby_warns%: returns the number of warns of the player.

#Actions

#You can use actions in the "actions:" or "events:"
#The right way to use your action is: [ACTION] content

#[MESSAGE] Send a message
#[TITLE] Send a title

#[FIREWORK] Summons a firework
#Ex.: [FIREWORK] BALL_LARGE, #FF00FF, #FFFF00, true, true, 1

#Ex.: [TITLE] &bWelcome!, Subtitle
#[BROADCAST] Advertise to everyone.

#[COMMAND] Make the player execute a command
#[CONSOLE] Make console execute a command

#[SOUND] play a sound
#[SOUND] ENTITY_EXPERIENCE_ORB_PICKUP, (Volume) 10.0, (Pitch) 10.0"

#[SUMMON] Summons an entity

#[EFFECT] give an effect to the player
#[EFFECT] effect, duration, amplifier

#[FLY] Makes the player fly

#[TP] teleport player for an exact location
#[TP] world, x, y, z (yaw, pictch)

#[OPEN] Opens an inventory
#[CLOSE] Closes an inventory
#There in the selectors.yml file you can create an inventory
#Mode of use: "[OPEN] (id)", "[CLOSE] "

#[PLAYER] returns the player's name (if you are not using PLACEHOLDER API)

#[HIDE] hide the players
#[SHOW] show the players
#[TOGGLE_HIDE] toggle the hide of the player

#[GAMEMODE] change the game mode of the player

#[CENTER] Centers your text according to Minecraft's default chat size
#It is an approximate centering according to the pixels of each letter in the game

#[PERMISSION] Only do the action if you have permission
#[OPEN] 1 [PERMISSION: your.permission]
#[OPEN] 1 [!PERMISSION: your.permission] (If you don't have permission)

#[ACTION] Send an action

#[PERMISSION] Only do the action if the condition is true
#[OPEN] 1 [IF: %xg7lobby_players_hiding%]
#[OPEN] 1 [!IF: #%xg7lobby_players_hiding%] (If the condition is false)

#Links:

#Items: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
#Sounds: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Sound.html
#Entities: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/Entity.html

###############################################
#GENERAL                                      #
###############################################

#Debug mode
debug: false

#Prefix
plugin-prefix: "&9[XG7&3Lob&bby] &8| &r"

#Will warn for a new version
warn-for-version: true

#Enabled worlds
enabled-worlds:
  - world

###############################################
#SQL                                          #
###############################################

#Cooldown to remove players on ram
sql-cache-expires: 30

sql:
  host: "localhost"
  port: "3306"
  database: "xg7lobbytest"

  user: "root"
  pass: "root"

###############################################
#LOBBY                                        #
###############################################

#Cooldown for tp
before-tp:
  cooldown-for-tp: 5
  dont-move: true

#Events on first join
on-first-join:
  enabled: true
  events:
    - "[TITLE] &bWelcome, &f%player_name%"
    - "[MESSAGE] [CENTER] &8-------------------&7**&8-------------------"
    - "[MESSAGE] [CENTER] &bWelcome &f%player_name%"
    - "[MESSAGE]  "
    - "[MESSAGE] [CENTER] &aSite: &fwww.website.com"
    - "[MESSAGE] [CENTER] &4YT: &fwww.youtube.com"
    - "[MESSAGE]  "
    - "[MESSAGE] [CENTER] &5&oPlugin made by DaviXG7"
    - "[MESSAGE] [CENTER] &8-------------------&7**&8-------------------"
    - "[SOUND] ENTITY_PLAYER_LEVELUP, 10.0, 0.0"
    - "[FIREWORK] BALL_LARGE, #FF0000, #FFFF00, true, true, 1"
    - "[FIREWORK] BALL_LARGE, #FF0000, #00FF00, true, true, 1"
    - "[FIREWORK] BALL_LARGE, #FF00FF, #00FFFF, true, true, 1"
    - "[FIREWORK] BALL_LARGE, #FF00FF, #FF00FF, true, true, 1"
    - "[FIREWORK] BALL_LARGE, #FF00FF, #FFFF00, true, true, 1"
    - "[OPEN] [!PERMISSION: xg7lobby.admin] 1"
    - "[COMMAND] [PERMISSION: xg7lobby.command.help] 7lhelp"

#Events on join
on-join:
  tp-to-lobby: true

  heal: true
  clear-inventory: true

  #Run events again when return to the world
  run-events-when-return-to-the-world: true

  events:
    - "[TITLE] &bWelcome, &f%player_name%"
    - "[MESSAGE] [CENTER] &8-------------------&7**&8-------------------"
    - "[MESSAGE] [CENTER] &bWelcome &f%player_name%"
    - "[MESSAGE]  "
    - "[MESSAGE] [CENTER] &aSite: &fwww.website.com"
    - "[MESSAGE] [CENTER] &4YT: &fwww.youtube.com"
    - "[MESSAGE]  "
    - "[MESSAGE] [CENTER] &5&oPlugin made by DaviXG7"
    - "[MESSAGE] [CENTER] &8-------------------&7**&8-------------------"
    - "[SOUND] ENTITY_EXPERIENCE_ORB_PICKUP, 10.0, 0.0"
    - "[FIREWORK] BALL_LARGE, #FF0000, #FFFF00, true, true, 1"
    - "[FIREWORK] BALL_LARGE, #FF0000, #00FF00, true, true, 1"
    - "[FIREWORK] BALL_LARGE, #FF00FF, #00FFFF, true, true, 1"
    - "[OPEN] [!PERMISSION: xg7lobby.admin] 1"
    - "[COMMAND] [PERMISSION: xg7lobby.command.help] 7lhelp"
    - "[SWAP] [IF: %xg7lobby_players_hiding%] 9, hide-players-on"
    - "[SWAP] [!IF: %xg7lobby_players_hiding%] 9, hide-players-off"


###############################################
#JUMPS                                        #
###############################################

launchpad:

  enabled: true

  top-block: STONE_PLATE
  bottom-block: AIR

  #Force of jump
  strength: 2
  jump: 1

  sound: "ENTITY_BAT_TAKEOFF, 1.0, 2.0"

double-jump:

  enabled: true

  #Force of jump
  strength: 2
  jump: 1

  sound: "ENTITY_BAT_TAKEOFF, 1.0, 2.0"

###############################################
#AUTO BROADCAST                               #
###############################################

auto-broadcast:

  enabled: true

  #Cooldown of ads in minutes
  cooldown: 3

  broadcast-only-in-the-lobby: false

  #Make the announcement random
  random: false

  sound: "ENTITY_EXPERIENCE_ORB_PICKUP, 5.0, 0.0"

  announcements:
    #Create your announcement
    #You can send in actionbars
    announcement1:
      - "[CENTER] &8-------------------&7**&8-------------------"
      - "[CENTER] &e&lANNOUNCEMENT:"
      - "[CENTER] &9This plugin was made by &bDaviXG7"
      - "[CENTER] &8-------------------&7**&8-------------------"
    announcement2:
      - "[CENTER] &8-------------------&7**&8-------------------"
      - "[CENTER] &e&lANNOUNCEMENT:"
      - "[CENTER] &aRate XG7Lobby in &e5 &bstars!"
      - "[CENTER] &8-------------------&7**&8-------------------"
    announcement3:
      - "[CENTER] &8-------------------&7**&8-------------------"
      - "[CENTER] &e&lANNOUNCEMENT:"
      - "[CENTER] &fVisit our website: &bhttps://xg7plugins.com"
      - "[CENTER] &8-------------------&7**&8-------------------"

###############################################
#MOTD                                         #
###############################################

#MOTD is the message that appears before
#join the server!
motd:
  enabled: true

  max-players: 9999

  text:
    - "[CENTER] &9XG7&3Lob&bby&r"
    - "[CENTER] &5&oMade by DaviXG7"

###############################################
#MODERATION                                   #
###############################################

warn-admin: false

warn-level-ban: 3
warn-level-kick: 2
warn-level-mute: 2

min-warns-level1-to-kick: 20
min-warns-level2-to-kick: 10
min-warns-level3-to-kick: 5
min-warns-total-to-kick: 50

warns-level1-to-ban: 50
warns-level2-to-ban: 25
warns-level3-to-ban: 12
warns-total-to-ban: 70

###############################################
#CHAT                                         #
###############################################

ignore-adm-for-lock-chat: true

anti-swearing:
  enabled: true

  #If you don't have permission and
  #if you send some this words
  #The message do not be sent, and
  #you will recive a warning

  #Try putting the words in lower case
  blocked-words:
    - "cu"
    - "wtf"
    - "fuck"
    - "porra"

block-commands:
  enabled: true

  anti-tab: true

  #If you don't have permission and
  #if you send some these commands
  #will block
  commands-blocked:
    - /pl
    - /plugins
    - /?
    - /bukkit:?
    - /bukkit:plugins
    - /bukkit:pl
    - /bukkit:help
    - /version
    - /bukkit:version
    - /bukkit:ver
    - /tell

anti-spam:
  enabled: true

  message-cannot-be-the-same: true

  #To send other message (IN SECONDS)
  cooldown: 0.5

  #Remove one spam from each player's list (IN SECONDS)
  spam-cooldown: 2

  #Messages tolerance
  tolerance: 10

  warn-tolerance: 5

  mute-on-spam-limit: true

  #To indeterminate and avoid errors, put "indeterminate"
  unmute-delay: "30m"

  warn-on-spam-limit: true
  spam-warn-level: 2
  warning: "&cMuted by spam"


###############################################
#PLAYER OPTIONS                               #
###############################################

player-task-delay: 5

effects:
  - "JUMP_BOOST, 1"
  - "SPEED, 2"

max-hearths: 2
cancel-death-by-void: true
hunger-loss: false
take-damage: false
cancel-portal: true
attack-entities: false

###############################################
#PVP                                          #
###############################################

pvp:
  enabled: true

  auto-respawn: true
  max-hearts: 10

  disable-launchpad: true
  disable-double-jump: true
  disable-fly: true

  take-damage: true

  #Cooldown to enable or disable the command (IN SECONDS)
  cooldown-to-toggle: 5

  #On use command will be cancelled
  dont-move-on-cmd: true

  #Drop the items on pvp
  drop-items: false

  blocked-commands-in-pvp:
    - "lobby"

  events-enable:
    - "[CONSOLE] clear [PLAYER]"
    - "[CONSOLE] give [PLAYER] diamond_sword"
  events-disable:
    - ""
  events-on-kill:
    - "[CONSOLE] give [KILLER] apple"
  events-on-respawn:
    - "[CONSOLE] clear [PLAYER]"
    - "[CONSOLE] give [PLAYER] diamond_sword"

#Interaction

# Only players who have the permission
# Will break blocks and place
break-blocks: false
place-blocks: false
interact-with-blocks: false

#Items: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
blocks-with-canceled-interaction:
  - "ANVIL"
  - "CHEST"
  - "CRAFTING_TABLE"
  - "HOPPER"
  - "FURNACE"
  - "OAK_TRAPDOOR"

#Drop, pick up

pickup-items: true
drop-items: false

###############################################
#SCORES                                       #
###############################################

scores-update: 5

tablist:

  enabled: true

  #Header of the tablist
  header:
    - "&9X&3G7&bLobby"
    - "&7Your rank: %luckperms_prefix%"
    - ""

  #Footer of the tablist
  footer:
    - ""
    - "&9Visit our website: &bwww.site.com"
    - "&5&oPlugin made by DaviXG7"

scoreboard:

  enabled: true

  #Scoreboard title
  #In older versions, the max is 32 characters!
  title: "&9XG7&3Lob&bby"

  #Lines of the score
  lines:
    - ""
    - "&e&lPlayer&f:"
    - "&fName: &9%player_name%"
    - "&fRank: &r[%prefix%]"
    - ""
    - "&fPlayers online: &a%server_online%"
    - ""
    - "&8www.example.com"


# ONLY WORKS +1.9
bossbar:

  enabled: true

  #Placeholders don't work here
  title: "&9&lWelcome to the server %player_name%"

  #See all colors here
  #https://helpch.at/docs/1.16.5/org/bukkit/boss/BarColor.html
  color: BLUE

  #See all styles here
  #https://helpch.at/docs/1.16.5/org/bukkit/boss/BarStyle.html
  style: SOLID

  #Goes from 0 to 1. For example: 0.5
  progress: 1


###############################################
#WORLD EVENTS                                 #
###############################################


world-task-delay: 20

#Define if mobs will spawn in the lobby
spawn-mobs: false

#Define the weather cycle on lobby world
storm: false

#Define the day cycle on lobby world
day-cycle: false

#Sunrise: 0
#Noon: 6000
#Sunset: 13000
#Midnight: 18000
time: 6000

#Define if the leaves will fall in the lobby
leaves-decay: false

#Define whether blocks will burn in the lobby
burn-blocks: false

block-spread: false

#Cancel explosions
cancel-explosions: true


###############################################
#WARN GUI OPTIONS                             #
###############################################

#Go in selectors.yml to learn more about items

warns-gui:

  title: "&6You have &9%xg7lobby_warns% warns &8%player_name%"

  fill-item: GRAY_STAINED_GLASS_PANE

  #To learn more about inv pos go to https://github.com/DaviXG7/XG7MenusAPI/tree/master
  inv-pos-1: [2,2]
  inv-pos-2: [8,5]

  #Do not supports skull

  warn-item-material-level-1: LIME_WOOL
  warn-item-material-level-2: YELLOW_WOOL
  warn-item-material-level-3: RED_WOOL

  warn-item:
    name: "&cWarn level [LEVEL]"
    lore:
      - "&9Date: &f[DATE]"
      - "&9Reason: &f[WARN]"
      - "&9ID: &7&o[ID]"

  go-next-page:
    name: "&aGo next"
    lore:
      - "&bUse this to go next"
    material: EMERALD
    slot: 54
  go-back-page:
    name: "&bGo back"
    lore:
      - "&bUse this to go back"
    material: REDSTONE
    slot: 46
