name: XG7Lobby
version: '${version}'
main: com.xg7plugins.xg7lobby.XG7Lobby
api-version: '1.16'

depend:
  - "XG7Plugins"

permissions:
  xg7lobby.admin:
    description: Permission to use the admin commands.
    default: op

  xg7lobby.command.*:
    description: Permission to use all commands.
    default: op
    children:
      xg7lobby.command.fly: true
      xg7lobby.command.gamemode: true
      xg7lobby.command.build: true
      xg7lobby.command.setlobby: true
      xg7lobby.command.lobby: true
      xg7lobby.command.moderation.*: true

  xg7lobby.command.moderation.*:
    description: Permission to use all moderation commands.
    default: op
    children:
      xg7lobby.command.moderation.kick: true
      xg7lobby.command.moderation.ban: true
      xg7lobby.command.moderation.unban: true
      xg7lobby.command.moderation.mute: true
      xg7lobby.command.moderation.unmute: true
      xg7lobby.command.moderation.tempban: true
      xg7lobby.command.moderation.tempmute: true
      xg7lobby.command.moderation.warn: true

  xg7lobby.attack:
    description: Permission to attack
    default: op

  xg7lobby.chat.*:
    description: Permission to use all chat restrictions.
    default: op
    children:
      xg7lobby.chat.swear: true
      xg7lobby.chat.ignore-lock: true
      xg7lobby.chat.spam: true
